### ISSUE TITLE
Alternatives to `/analyses/history` endpoint for on-premise deployments

### ISSUE THREAD

**Issue by cccs-kevin** [intezer/analyze-python-sdk#126]
Hi Intezer!

I would like to retrieve the history of analyses for the last 2 years, but the `/analyses/history` endpoint is not available for my on-premise deployment (v22.10). 

Is there a work-around / alternative endpoint that I could use via the Python client to get this data?

Thanks,

Kevin

**Comment by Nataly-Shvartzman** [comment]
Hi Kevin!

Thank you for reaching out to us.
We are about to release a new on-premise version in the coming weeks, and this capability will be included there.
