### ISSUE TITLE
Unimplemented Endpoint: GET analyses/:analysis-id/detect

### ISSUE THREAD

**Issue by notgriffin** [intezer/analyze-python-sdk#30]
The Intezer API documentation has documentation for the endpoint `GET analyses/:analysis-id/detect` and hitting the API shows it is active, but the SDK does not have a specific function for this endpoint. Can a function for this endpoint please be added? Thanks!

**Comment by cccs-kevin** [comment]
Hey @notgriffin, my Intezer API documentation does not describe the endpoint that you mention above?

**Comment by notgriffin** [comment]
Here is a link

https://analyze.intezer.com/api/docs/documentation#get-analysesanalysis-iddetect

**Comment by cccs-kevin** [comment]
> Here is a link
> 
> https://analyze.intezer.com/api/docs/documentation#get-analysesanalysis-iddetect

Shoot, I don't have an account with the public `analyze.intezer.com` instance so I can't view the link. I'm guessing the docs there indicate that the endpoint exists?

I tested hitting that endpoint on my private Intezer Analze instance and got a 404 saying that the endpoint doesn't exist. @AvihayST @kfirstri @doronshemtov Is there a reason that this endpoint would be on the public Intezer instance and not my private one?

**Comment by cccs-kevin** [comment]
@notgriffin I signed up with a community account and the API docs dn't contain that endpoint, are you a premium user?

**Comment by notgriffin** [comment]
> @notgriffin I signed up with a community account and the API docs don't contain that endpoint, are you a premium user?

Yes I am
